# Generated by Django 5.2.7 on 2025-10-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('temp_min', models.FloatField(default=2.0)),
                ('temp_max', models.FloatField(default=8.0)),
                ('humidity_min', models.FloatField(default=30.0)),
                ('humidity_max', models.FloatField(default=70.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.transportbox')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.sample')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'severity'], name='core_alert_is_acti_569804_idx'), models.Index(fields=['box', 'is_active'], name='core_alert_box_id_960e63_idx'), models.Index(fields=['sample', 'is_active'], name='core_alert_sample__080bbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('geolocation', models.CharField(blank=True, default='', max_length=255)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.transportbox')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.sample')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='core_teleme_timesta_fb8d19_idx'), models.Index(fields=['box', 'timestamp'], name='core_teleme_box_id_df546e_idx'), models.Index(fields=['sample', 'timestamp'], name='core_teleme_sample__22f553_idx')],
            },
        ),
    ]
