name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: bio_supply_twin_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d bio_supply_twin_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r backend/requirements-test.txt

    - name: Run Django tests
      env:
        DJANGO_SETTINGS_MODULE: bio_supply_twin.settings
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/bio_supply_twin_test
      run: |
        cd backend
        python manage.py migrate
        python manage.py test
        
    - name: Run FastAPI tests
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/bio_supply_twin_test
      run: |
        cd backend
        pytest digital_twin_service/tests/
        